/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/ActionButton.vue')['default']
    ActionButtonsrow: typeof import('./src/components/ActionButtonsrow.vue')['default']
    AppLayout: (typeof import('./src/layouts/AppLayout.vue'))['default']
    DeleteNotebutton: typeof import('./src/components/DeleteNotebutton.vue')['default']
    DraggableTopbar: typeof import('./src/components/DraggableTopbar.vue')['default']
    FloatingNoteTitle: typeof import('./src/components/FloatingNoteTitle.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    NewNotebutton: typeof import('./src/components/NewNotebutton.vue')['default']
    NotePreview: typeof import('./src/components/NotePreview.vue')['default']
    NotePreviewList: typeof import('./src/components/NotePreviewList.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
